// GENERATED by scripts/blueprint-build.mjs from vendor/event-blueprint/src/{data,bench}.js.
// Do not edit: the option lists the Blueprint's server-side AI prompts name.
export const BLUEPRINT_CATALOGS = {
  "TYPES": [
    {
      "id": "summit",
      "n": "Corporate conference or summit"
    },
    {
      "id": "launch",
      "n": "Product launch"
    },
    {
      "id": "expo",
      "n": "Trade show or expo"
    },
    {
      "id": "gala",
      "n": "Awards night or gala dinner"
    },
    {
      "id": "training",
      "n": "Workshop or masterclass"
    },
    {
      "id": "webinar",
      "n": "Webinar or virtual series"
    },
    {
      "id": "festival",
      "n": "Festival or concert"
    },
    {
      "id": "sports",
      "n": "Sports event"
    },
    {
      "id": "community",
      "n": "Community or cultural event"
    },
    {
      "id": "private",
      "n": "Wedding or private celebration"
    },
    {
      "id": "exhibition",
      "n": "Exhibition, museum or gallery"
    },
    {
      "id": "hackathon",
      "n": "Hackathon or competition"
    },
    {
      "id": "congress",
      "n": "Medical or scientific congress"
    },
    {
      "id": "other",
      "n": "Something else"
    }
  ],
  "FORMATS": [
    "In person",
    "Hybrid",
    "Virtual",
    "Online world only"
  ],
  "GOALS": [
    "Educate",
    "Launch something",
    "Celebrate",
    "Network and connect",
    "Generate leads or sales",
    "Raise funds",
    "Build community",
    "Recognise or award",
    "Entertain",
    "Align a team"
  ],
  "MOODS": [
    "Premium",
    "Warm",
    "Scientific",
    "Bold",
    "Calm",
    "Playful",
    "Futuristic",
    "Heritage",
    "Intimate",
    "Energetic",
    "Minimal",
    "Festive",
    "Natural",
    "Corporate",
    "Artistic",
    "Regional and local"
  ],
  "LANGS": [
    "English",
    "Arabic",
    "French",
    "Hindi",
    "Urdu",
    "Spanish",
    "Mandarin"
  ],
  "LOOKS": [
    "Elegant",
    "Clean and precise",
    "Warm and natural",
    "High-tech",
    "Luxury",
    "Colourful",
    "Monochrome",
    "Industrial",
    "Traditional",
    "Editorial"
  ],
  "SETTINGS": [
    "Hotel ballroom",
    "Convention centre",
    "Rooftop",
    "Desert camp",
    "Beach",
    "Museum or gallery",
    "Garden or park",
    "Theatre",
    "Stadium or arena",
    "Industrial warehouse",
    "Heritage site",
    "Purely imaginary world"
  ],
  "FEATURES": [
    "Walk the venue in 3D",
    "Watch live or recorded sessions",
    "Talk to AI attendees",
    "Meet real attendees as avatars",
    "Visit booths or stands",
    "Live Q&A and polls",
    "Networking matchmaking",
    "Certificates or credits",
    "Buy tickets or products",
    "Vote or judge",
    "Photo moments and sharing",
    "Challenges and leaderboards",
    "On-demand library",
    "Captions and translation"
  ],
  "ACCESS": [
    "Open link",
    "Free registration",
    "Paid ticket",
    "Invite only",
    "Company or member login"
  ],
  "REGULATED": [
    "None",
    "Pharma or medical devices",
    "Alcohol",
    "Financial services",
    "Gaming or betting",
    "Other regulated"
  ],
  "LAYOUT_NAMES": [
    "Theatre",
    "Classroom",
    "Banquet rounds",
    "Cabaret",
    "Standing reception",
    "Boardroom",
    "U-shape",
    "Exhibition stands",
    "Standing crowd",
    "Open or mixed",
    "Online only"
  ]
} as const;
