/**
 * Meeting Minds' product/service catalog — the seed for the org's CRM product list.
 *
 * Client-safe (no `db`). Baked from the Jan-2026 QuickBooks product list; seeded once
 * per org by `ensureCrmProducts` (like the pipeline stages / email templates), then
 * maintained via CRUD on the Products tab. `category` is the FUNCTIONAL group (derived
 * from the SKU/name prefix — Content, Sponsorship, Design, …), distinct from `source`
 * (In-House vs Out-Sourced). `price` is the catalog LIST price in AED — on a deal it
 * pre-fills the line item, but the actual line price is set manually there.
 */
export type CrmProductSource = "IN_HOUSE" | "OUTSOURCED";

export interface CrmProductSeed {
  name: string;
  sku: string;
  category: string;
  source: CrmProductSource;
  /** Catalog list price (AED). Pre-fills a deal line item; editable per deal. */
  price: number;
}

/** The functional categories present in the seed, for pickers/filters. */
export const CRM_PRODUCT_CATEGORIES: readonly string[] = ["Abstract Management", "CME", "Communication", "Content", "Delegate Sales", "Design", "Endorsements", "Event Management", "Exhibition", "F&B", "Finance", "Giveaways", "Hospitality", "Misc", "Permits", "Production", "Project Management", "Setup & Build", "Sponsorship", "Staffing", "Travel", "Venue Hire", "Virtual"];

export const CRM_PRODUCT_SEED: readonly CrmProductSeed[] = [
  { name: "Abstract Management - Reviewer Portal", sku: "ABS10001", category: "Abstract Management", source: "IN_HOUSE", price: 7340 },
  { name: "Abstract Management - Submission Portal", sku: "ABS10002", category: "Abstract Management", source: "IN_HOUSE", price: 7340 },
  { name: "Abstract Management - (per abstract)", sku: "ABS10003", category: "Abstract Management", source: "IN_HOUSE", price: 175 },
  { name: "CME - Application Fees", sku: "CME10001", category: "CME", source: "OUTSOURCED", price: 1 },
  { name: "CME - Application Processing", sku: "CME10002", category: "CME", source: "IN_HOUSE", price: 7340 },
  { name: "CME - Fullfilment", sku: "CME10003", category: "CME", source: "IN_HOUSE", price: 7340 },
  { name: "CME - E-Certificate (per certificate)", sku: "CME10004", category: "CME", source: "IN_HOUSE", price: 20 },
  { name: "CME - Evaluation Survey (per user)", sku: "CME10005", category: "CME", source: "IN_HOUSE", price: 20 },
  { name: "Communcation - Email Marketing (per email)", sku: "COM10001", category: "Communication", source: "IN_HOUSE", price: 3670 },
  { name: "Communcation - Landing Page", sku: "COM10002", category: "Communication", source: "IN_HOUSE", price: 6422.5 },
  { name: "Communcation - Mobile App", sku: "COM10003", category: "Communication", source: "IN_HOUSE", price: 18350 },
  { name: "Communcation - Press Release", sku: "COM10004", category: "Communication", source: "IN_HOUSE", price: 3670 },
  { name: "Communcation Social Media Management (per month)", sku: "COM10005", category: "Communication", source: "IN_HOUSE", price: 3670 },
  { name: "Communcation - Web Site Development", sku: "COM10006", category: "Communication", source: "IN_HOUSE", price: 22020 },
  { name: "Communcation - Online Advertising", sku: "COM10007", category: "Communication", source: "OUTSOURCED", price: 1 },
  { name: "Communcation - Overseas Marketing", sku: "COM10008", category: "Communication", source: "OUTSOURCED", price: 1 },
  { name: "Communcation - Social Media Campaign (PPC)", sku: "COM10009", category: "Communication", source: "OUTSOURCED", price: 1 },
  { name: "Content - Abstract Book (per abstract)", sku: "CON10001", category: "Content", source: "IN_HOUSE", price: 250 },
  { name: "Content - Proof Reading (per page)", sku: "CON10002", category: "Content", source: "IN_HOUSE", price: 750 },
  { name: "Content - Digital Magazine (per page)", sku: "CON10003", category: "Content", source: "IN_HOUSE", price: 3670 },
  { name: "Content - Digital Newsletter", sku: "CON10004", category: "Content", source: "IN_HOUSE", price: 2752.5 },
  { name: "Content - Final Program (per page)", sku: "CON10005", category: "Content", source: "IN_HOUSE", price: 150 },
  { name: "Content - Medical Article (per page)", sku: "CON10006", category: "Content", source: "IN_HOUSE", price: 3670 },
  { name: "Content - Slide-show as per Running Order", sku: "CON10007", category: "Content", source: "IN_HOUSE", price: 5505 },
  { name: "Content - Sponsorship Prospectus", sku: "CON10008", category: "Content", source: "IN_HOUSE", price: 7340 },
  { name: "Content - Story Board Writing (per script)", sku: "CON10009", category: "Content", source: "IN_HOUSE", price: 3670 },
  { name: "Content - Video Production (per minute)", sku: "CON10010", category: "Content", source: "IN_HOUSE", price: 5505 },
  { name: "Content - Medical Writing (per word)", sku: "CON10011", category: "Content", source: "OUTSOURCED", price: 1 },
  { name: "Content - Advisory Board", sku: "CON10012", category: "Content", source: "OUTSOURCED", price: 1 },
  { name: "Delegate Sales - Early Bird Registration", sku: "DEL10001", category: "Delegate Sales", source: "IN_HOUSE", price: 1 },
  { name: "Delegate Sales - Standard Registration", sku: "DEL10002", category: "Delegate Sales", source: "IN_HOUSE", price: 1 },
  { name: "Design - Animated Graphics", sku: "DES10001", category: "Design", source: "IN_HOUSE", price: 1 },
  { name: "Design - Event Brand Identity", sku: "DES10002", category: "Design", source: "IN_HOUSE", price: 11010 },
  { name: "Design - Event Flyer", sku: "DES10003", category: "Design", source: "IN_HOUSE", price: 1850 },
  { name: "Design - HTML Announcement", sku: "DES10004", category: "Design", source: "IN_HOUSE", price: 1850 },
  { name: "Design - Other Graphic Design", sku: "DES10005", category: "Design", source: "IN_HOUSE", price: 1 },
  { name: "Design - Presentation Template", sku: "DES10006", category: "Design", source: "IN_HOUSE", price: 3670 },
  { name: "Design - Stage Design", sku: "DES10007", category: "Design", source: "IN_HOUSE", price: 7340 },
  { name: "Design - Event Invitation", sku: "DES10008", category: "Design", source: "IN_HOUSE", price: 1850 },
  { name: "Endorsements - Society", sku: "END10001", category: "Endorsements", source: "OUTSOURCED", price: 1 },
  { name: "Endorsements - Society Royalty Fees", sku: "END10002", category: "Endorsements", source: "OUTSOURCED", price: 1 },
  { name: "Event Management - Badge Scanners (per scanner)", sku: "EVE10001", category: "Event Management", source: "IN_HOUSE", price: 1200 },
  { name: "Event Management - Equipment Rental", sku: "EVE10002", category: "Event Management", source: "IN_HOUSE", price: 1 },
  { name: "Event Management - POS Machines (per machine)", sku: "EVE10003", category: "Event Management", source: "IN_HOUSE", price: 750 },
  { name: "Event Management - Registration Portal", sku: "EVE10004", category: "Event Management", source: "IN_HOUSE", price: 3670 },
  { name: "Event Management - Session Management", sku: "EVE10005", category: "Event Management", source: "IN_HOUSE", price: 1 },
  { name: "Event Management - Master of Ceremony", sku: "EVE10006", category: "Event Management", source: "OUTSOURCED", price: 1 },
  { name: "Exhibition - Shell Scheme Stand (per sqm)", sku: "EXH10001", category: "Exhibition", source: "IN_HOUSE", price: 3670 },
  { name: "Exhibition - Space Only Stand (per sqm)", sku: "EXH10002", category: "Exhibition", source: "IN_HOUSE", price: 2950 },
  { name: "Finance - Bank Charges", sku: "FIN10001", category: "Finance", source: "IN_HOUSE", price: 1 },
  { name: "Finance - Cost of Funds", sku: "FIN10002", category: "Finance", source: "IN_HOUSE", price: 1 },
  { name: "Finance - Currency Variation", sku: "FIN10003", category: "Finance", source: "IN_HOUSE", price: 1 },
  { name: "Finance - Insurance", sku: "FIN10004", category: "Finance", source: "IN_HOUSE", price: 12000 },
  { name: "F&B - Faculty Dinner", sku: "FNB10001", category: "F&B", source: "OUTSOURCED", price: 1 },
  { name: "F&B - Networking Dinner", sku: "FNB10002", category: "F&B", source: "OUTSOURCED", price: 1 },
  { name: "F&B - Welcome Reception", sku: "FNB10003", category: "F&B", source: "OUTSOURCED", price: 1 },
  { name: "Giveaways - Delegate Packs (per user)", sku: "GIV10001", category: "Giveaways", source: "OUTSOURCED", price: 1 },
  { name: "Giveaways - Speaker Trophies", sku: "GIV10002", category: "Giveaways", source: "OUTSOURCED", price: 1 },
  { name: "Hospitality - Air Travel Booking Fee", sku: "HOS10001", category: "Hospitality", source: "IN_HOUSE", price: 175 },
  { name: "Hospitality - Hotel Booking Fee", sku: "HOS10002", category: "Hospitality", source: "IN_HOUSE", price: 175 },
  { name: "Hospitality - Accommodation Portal", sku: "HOS10003", category: "Hospitality", source: "IN_HOUSE", price: 3670 },
  { name: "Hospitality - Visa Application Fee", sku: "HOS10004", category: "Hospitality", source: "IN_HOUSE", price: 175 },
  { name: "Misc - Courier Charges", sku: "MIS10001", category: "Misc", source: "OUTSOURCED", price: 1 },
  { name: "Misc - Stationery", sku: "MIS10002", category: "Misc", source: "OUTSOURCED", price: 1 },
  { name: "Misc - Freight & Shipping", sku: "MIS10003", category: "Misc", source: "OUTSOURCED", price: 1 },
  { name: "Misc - Labour Charges", sku: "MIS10004", category: "Misc", source: "OUTSOURCED", price: 1 },
  { name: "Misc - Other Expenses", sku: "MIS10005", category: "Misc", source: "OUTSOURCED", price: 1 },
  { name: "Permits - Event Permit Abu Dhabi", sku: "PER10001", category: "Permits", source: "OUTSOURCED", price: 1 },
  { name: "Permits - Event Permit Dubai", sku: "PER10002", category: "Permits", source: "OUTSOURCED", price: 1 },
  { name: "Permits - Speaker Permit Abu Dhabi", sku: "PER10003", category: "Permits", source: "OUTSOURCED", price: 1 },
  { name: "Project Management - Event Report", sku: "PRJ10001", category: "Project Management", source: "IN_HOUSE", price: 3670 },
  { name: "Project Management - PCO Fees", sku: "PRJ10002", category: "Project Management", source: "IN_HOUSE", price: 1 },
  { name: "Production - Event Signage", sku: "PRO10001", category: "Production", source: "OUTSOURCED", price: 1 },
  { name: "Production - Printing", sku: "PRO10002", category: "Production", source: "OUTSOURCED", price: 1 },
  { name: "Production - Venue Branding", sku: "PRO10003", category: "Production", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Translation Services (per language)", sku: "SET10001", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Videography", sku: "SET10002", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Voting System", sku: "SET10003", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Audio Video Equipment", sku: "SET10004", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Badges & Lanyards", sku: "SET10005", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Custom Welcome Desk", sku: "SET10006", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Digital Kiosk", sku: "SET10007", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Digital Posters", sku: "SET10008", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Exhibition Build", sku: "SET10009", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Faculty Lounge", sku: "SET10010", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Furniture Rental", sku: "SET10011", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Networking & Cabling", sku: "SET10012", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Photography", sku: "SET10013", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Poster Area Build (Per Pannel)", sku: "SET10014", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Power Supply", sku: "SET10015", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Self Service Registration (per counter)", sku: "SET10016", category: "Setup & Build", source: "IN_HOUSE", price: 7340 },
  { name: "Setup & Build - Special Features", sku: "SET10017", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Setup & Build - Florist", sku: "SET10018", category: "Setup & Build", source: "OUTSOURCED", price: 1 },
  { name: "Sponsorship - Diamond", sku: "SPO10001", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Gold", sku: "SPO10002", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Breakfast Symposium", sku: "SPO10003", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Lunch Symposium", sku: "SPO10004", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Platinum", sku: "SPO10005", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Silver", sku: "SPO10006", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Support", sku: "SPO10007", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Delegates", sku: "SPO10008", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Workshop", sku: "SPO10009", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Industry Symposium", sku: "SPO10010", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Exhibitor", sku: "SPO10011", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Sponsorship - Industry Partner", sku: "SPO10012", category: "Sponsorship", source: "IN_HOUSE", price: 1 },
  { name: "Staffing - Staff Visa", sku: "STA10001", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Staffing - Staff Accommodation", sku: "STA10002", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Staffing - Staff Air Travel", sku: "STA10003", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Staffing - Staff Hire (per hour)", sku: "STA10004", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Staffing - Staff Per-Diem", sku: "STA10005", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Staffing - Staff Refreshments", sku: "STA10006", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Staffing - Staff Transportation", sku: "STA10007", category: "Staffing", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Air Tickets", sku: "TRA10001", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Bus Transfers", sku: "TRA10002", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Chauffeur Transfers", sku: "TRA10003", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Hotel Accommodation", sku: "TRA10004", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Honoraria", sku: "TRA10005", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Reimbursement", sku: "TRA10006", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Travel - Visa Fees", sku: "TRA10007", category: "Travel", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Day Delegate Rate", sku: "VEN10001", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Exhibition Hall", sku: "VEN10002", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Meeting Rooms", sku: "VEN10003", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Session Halls", sku: "VEN10004", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Venue Barriers", sku: "VEN10005", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Carpeting", sku: "VEN10006", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Internet Charges", sku: "VEN10007", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - Wifi Network", sku: "VEN10008", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Venue Hire - VIP Lounge", sku: "VEN10009", category: "Venue Hire", source: "OUTSOURCED", price: 1 },
  { name: "Virtual - Live Webinar", sku: "VIR10001", category: "Virtual", source: "IN_HOUSE", price: 18350 },
  { name: "Virtual - Session Pre-recording (per hour)", sku: "VIR10002", category: "Virtual", source: "IN_HOUSE", price: 1850 },
  { name: "Virtual - Hybrid Streaming", sku: "VIR10003", category: "Virtual", source: "IN_HOUSE", price: 36700 },
];
