/**
 * Quote without Pay Now (Aug 11, 2026). Presenter plan D3.
 *
 * An abstract submitter is told the amount and gets the quote PDF, but is not
 * INVITED to pay yet: on the organizer's own figure roughly 29 in 30 are comped
 * once their abstract is accepted, and a payment taken now would have to be
 * refunded through a credit note.
 *
 * The distinction that matters, and the reason this is not the existing
 * `coveredByGroupPayerName` flag: that one means SOMEBODY ELSE is paying, so
 * the quote is suppressed too. Here the registrant genuinely owes it, just not
 * yet, so the quote must survive and only the call to action goes.
 *
 * These drive the REAL sendRegistrationConfirmation against a mocked
 * transport, rather than asserting on source text. A test that re-implements
 * the branch it is checking proves only that the copy in the test works.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";

const { sesSendMock } = vi.hoisted(() => ({ sesSendMock: vi.fn() }));

vi.mock("@/lib/logger", () => ({
  apiLogger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));
vi.mock("@/lib/email-log", () => ({ logEmail: vi.fn(async () => undefined) }));
vi.mock("@/lib/db", () => ({ db: {}, dbOperator: {}, tenantTransaction: vi.fn() }));
// The quote PDF is generated by pdfkit; stub it so these stay fast and so we
// can assert on WHETHER it was attached rather than on its bytes.
vi.mock("@/lib/quote-pdf", () => ({
  generateQuotePDF: vi.fn(async () => Buffer.from("%PDF-quote")),
  buildQuotePDFFromRegistration: vi.fn(),
}));
vi.mock("@aws-sdk/client-sesv2", () => ({
  SESv2Client: class {
    send = sesSendMock;
    get config() {
      return { credentials: async () => ({ accessKeyId: "AKIATEST" }) };
    }
  },
  SendEmailCommand: class {
    constructor(public input: unknown) {}
  },
}));

import { sendRegistrationConfirmation } from "@/lib/email";

const BASE = {
  to: "presenter@hospital.org",
  firstName: "Jane",
  lastName: "Doe",
  eventName: "MEHF 2027",
  eventSlug: "mehf-2027",
  eventDate: new Date("2027-03-01T09:00:00.000Z"),
  eventVenue: "Raffles",
  eventCity: "Dubai",
  ticketType: "Physician",
  registrationId: "reg_1",
  serialId: 7,
  qrCode: "1234567890",
  ticketPrice: 400,
  ticketCurrency: "USD",
};

/** Same registration, but with the org set, which is what makes the quote attach. */
const WITH_QUOTE = { ...BASE, organizationName: "Meeting Minds" };

/**
 * The rendered HTML of the single email this send produced.
 *
 * Only valid when the send carried NO attachment: with one, sendEmail switches
 * to raw MIME and the body arrives as quoted-printable bytes, which is not
 * something to string-match against. So the copy assertions use a fixture with
 * no quote (BASE), and the "quote still attaches" property is asserted
 * separately by looking for the raw-MIME envelope.
 */
function renderedHtml(): string {
  expect(sesSendMock).toHaveBeenCalled();
  const input = sesSendMock.mock.calls[0][0].input as {
    Content?: { Simple?: { Body?: { Html?: { Data?: string } } } };
  };
  const html = input.Content?.Simple?.Body?.Html?.Data;
  expect(html, "expected a Simple (unattached) email; add no organizationName").toBeTruthy();
  return html as string;
}

/** True when the send went out as raw MIME, which only happens with attachments. */
function hadAttachment(): boolean {
  const input = sesSendMock.mock.calls[0][0].input as { Content?: { Raw?: unknown } };
  return Boolean(input.Content?.Raw);
}

beforeEach(() => {
  vi.clearAllMocks();
  sesSendMock.mockResolvedValue({ MessageId: "m1" });
});

describe("sendRegistrationConfirmation with suppressPayNow", () => {
  it("still tells them the amount", async () => {
    await sendRegistrationConfirmation({ ...BASE, suppressPayNow: true });
    expect(renderedHtml()).toContain("400");
  });

  it("drops the Pay Now call to action", async () => {
    await sendRegistrationConfirmation({ ...BASE, suppressPayNow: true });
    expect(renderedHtml()).not.toContain("Pay Now");
  });

  it("keeps Pay Now when not suppressed, so the default path is unchanged", async () => {
    await sendRegistrationConfirmation({ ...BASE, suppressPayNow: false });
    expect(renderedHtml()).toContain("Pay Now");
  });

  it("is off by default when the caller says nothing", async () => {
    await sendRegistrationConfirmation({ ...BASE });
    expect(renderedHtml()).toContain("Pay Now");
  });

  /**
   * The line it replaces said the registration was incomplete until payment
   * arrived, which would be untrue for someone about to be comped.
   */
  it("does not claim the registration is incomplete until they pay", async () => {
    await sendRegistrationConfirmation({ ...BASE, suppressPayNow: true });
    const html = renderedHtml();
    expect(html).not.toContain("upon receipt of your payment");
    expect(html).toContain("once your submission has been reviewed");
  });

  /**
   * THE property that separates this from coveredByGroupPayerName. Suppressing
   * the call to action must not suppress the document: an amount with no quote
   * is worse than either alone.
   */
  it("still attaches the quote PDF", async () => {
    await sendRegistrationConfirmation({ ...WITH_QUOTE, suppressPayNow: true });
    expect(hadAttachment()).toBe(true);
  });

  it("relabels the block, since nothing is pending on the submitter", async () => {
    await sendRegistrationConfirmation({ ...BASE, suppressPayNow: true });
    const html = renderedHtml();
    expect(html).toContain("Registration Fee");
    expect(html).not.toContain("Payment Pending");
  });
});
