import type { PermissionKey } from "@/lib/permissions/catalogue";

/**
 * The permission each agent tool needs (custom roles Phase 3, Oct 5, 2026):
 * the key the matching REST route asks, so the agent can do exactly what the
 * person could do on the screens. A tool missing here is refused (fail
 * closed); `tool-permissions.test.ts` fails when a registered tool has no key.
 * For an event-bound key the event is the call's `eventId`, else the event
 * the agent was opened on.
 */
export const TOOL_PERMISSIONS: Readonly<Record<string, PermissionKey>> = {
  // Events
  list_events: "events.read",
  search_event: "events.read",
  get_event_info: "events.read",
  get_event_stats: "events.read",
  get_event_dashboard: "events.read",
  create_event: "events.create",
  update_event: "events.update",
  get_event_analytics: "analytics.read",
  // Contacts
  list_contacts: "contacts.read",
  create_contact: "contacts.write",
  update_contact: "contacts.write",
  // Program
  list_tracks: "sessions.read",
  list_sessions: "sessions.read",
  list_live_sessions_now: "sessions.read",
  list_zoom_meetings: "sessions.read",
  create_track: "tracks.write",
  create_session: "sessions.write",
  update_session: "sessions.write",
  add_topic_to_session: "sessions.write",
  add_speaker_to_session: "sessions.write",
  remove_speaker_from_session: "sessions.write",
  replace_session_speakers: "sessions.write",
  create_zoom_meeting: "zoom.meetings.manage",
  // Speakers
  list_speakers: "speakers.read",
  list_speaker_agreements: "speakers.read",
  get_speaker_agreement_template: "speakers.read",
  create_speaker: "speakers.create",
  create_speakers_bulk: "speakers.import",
  update_speaker: "speakers.update",
  upload_speaker_agreement_template: "speakers.agreements.manage",
  // Registrations and types
  list_ticket_types: "tickets.read",
  create_ticket_type: "tickets.write",
  list_registrations: "registrations.read",
  create_registration: "registrations.create",
  create_registrations_bulk: "registrations.import",
  update_registration: "registrations.update",
  bulk_update_registration_status: "registrations.bulk",
  check_in_registration: "registrations.checkin",
  list_unpaid_registrations: "finance.view",
  list_promo_codes: "promo.read",
  create_promo_code: "promo.write",
  update_promo_code: "promo.write",
  delete_promo_code: "promo.delete",
  // Abstracts
  list_abstracts: "abstracts.read",
  list_abstract_themes: "abstracts.read",
  list_review_criteria: "abstracts.read",
  get_abstract_scores: "abstracts.read",
  list_reviewers: "reviewers.pool.manage",
  create_abstract_theme: "abstracts.themes.manage",
  create_review_criterion: "abstracts.criteria.manage",
  update_review_criterion: "abstracts.criteria.manage",
  update_abstract_status: "abstracts.decide",
  assign_reviewer_to_abstract: "abstracts.reviewers.assign",
  unassign_reviewer_from_abstract: "abstracts.reviewers.assign",
  submit_abstract_review: "abstracts.decide",
  admin_submit_review_on_behalf: "abstracts.decide",
  // Accommodation
  list_hotels: "accommodation.read",
  list_room_types: "accommodation.read",
  list_accommodations: "accommodation.read",
  create_hotel: "hotels.manage",
  create_room_type: "hotels.manage",
  update_room_type: "hotels.manage",
  delete_room_type: "hotels.manage",
  create_accommodation: "accommodation.write",
  update_accommodation_status: "accommodation.write",
  // Money
  list_invoices: "invoices.read",
  create_invoice: "invoices.write",
  send_invoice: "invoices.send",
  update_invoice_status: "invoices.write",
  // Communications
  list_email_templates: "templates.read",
  create_email_template: "templates.manage",
  update_email_template: "templates.manage",
  duplicate_email_template: "templates.manage",
  reset_email_template: "templates.manage",
  send_bulk_email: "communications.send",
  list_scheduled_emails: "communications.schedule",
  cancel_scheduled_email: "communications.schedule",
  list_media: "media.library.manage",
  // Certificates
  list_certificate_templates: "certificates.read",
  create_certificate_template: "certificates.templates.manage",
  update_certificate_template: "certificates.templates.manage",
  update_cme_settings: "certificates.templates.manage",
  // Webinar, sponsors, RSVP
  get_webinar_info: "webinar.analytics.read",
  list_webinar_attendance: "webinar.analytics.read",
  list_webinar_engagement: "webinar.analytics.read",
  list_sponsors: "sponsors.read",
  upsert_sponsors: "sponsors.manage",
  research_sponsor: "sponsors.manage",
  list_rsvps: "rsvp.roster.read",
  // CRM
  list_crm_pipeline: "crm.read",
  list_crm_deals: "crm.read",
  list_crm_deal_types: "crm.read",
  get_crm_deal: "crm.read",
  list_crm_companies: "crm.read",
  get_crm_company: "crm.read",
  list_crm_tasks: "crm.read",
  list_crm_contacts: "crm.read",
  list_crm_products: "crm.read",
  list_crm_deal_products: "crm.read",
  get_crm_report: "crm.read",
  create_crm_deal: "crm.write",
  update_crm_deal: "crm.write",
  move_crm_deal_stage: "crm.write",
  close_crm_deal: "crm.write",
  create_crm_company: "crm.write",
  update_crm_company: "crm.write",
  create_crm_task: "crm.write",
  complete_crm_task: "crm.write",
  add_crm_note: "crm.write",
  create_crm_contact: "crm.write",
  update_crm_contact: "crm.write",
  create_crm_product: "crm.write",
  update_crm_product: "crm.write",
  add_deal_product: "crm.write",
  update_deal_product: "crm.write",
  // Budgets
  list_budgets: "procurement.budgets.view",
  get_budget: "procurement.budgets.view",
  list_budget_categories: "procurement.budgets.view",
  list_budget_templates: "procurement.budgets.view",
  list_spend_requests: "procurement.requests.view",
  list_commitments: "procurement.orders.view",
  create_budget: "procurement.budgets.create",
  add_budget_lines: "procurement.budgets.edit",
  replace_budget_lines: "procurement.budgets.edit",
};

export function toolPermission(toolName: string): PermissionKey | null {
  return TOOL_PERMISSIONS[toolName] ?? null;
}
