#!/usr/bin/env node
/**
 * Rebuild the Event Blueprint page EA-SYS serves at /blueprint.
 *
 *   npm run blueprint:build             # the vendor's own build.py (python3)
 *   npm run blueprint:build -- --node   # the same join in Node, no Python needed
 *   BLUEPRINT_BUILDER=node npm run blueprint:build
 *
 * Two interchangeable builders, owner's choice (Oct 8, 2026): keep the vendor's
 * Python toolchain, with a Node one beside it so a machine without Python is
 * never stuck. Both write the same bytes to vendor/event-blueprint/dist/
 * (index.html, and test.html for the vendor's own browser suites); the
 * page-html test proves the Node join equals dist/index.html.
 *
 * Then the page is written into src/lib/blueprint/page-html.generated.json, so
 * the server bundle carries it and no file has to be traced into the
 * standalone build. Run this after ANY change under vendor/event-blueprint/src/.
 * Python is never needed on the server: it only ever runs here, on a laptop.
 */
import { execFileSync } from "node:child_process";
import vm from "node:vm";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VENDOR = path.join(ROOT, "vendor/event-blueprint");
const DIST = path.join(VENDOR, "dist");
const OUT = path.join(ROOT, "src/lib/blueprint/page-html.generated.json");
const CATALOGS_OUT = path.join(ROOT, "src/lib/blueprint/catalogs.generated.ts");

const useNode = process.argv.includes("--node") || process.env.BLUEPRINT_BUILDER === "node";

/** build.py, line for line: part1.html, then the four scripts in one <script>. */
function joinVendorPage(vendorDir) {
  const src = (f) => readFileSync(path.join(vendorDir, "src", f), "utf8");
  const js = ["data.js", "bench.js", "platform.js", "app.js"].map(src).join("\n");
  return src("part1.html") + "\n<script>\n" + js + "\n</script>\n";
}

function buildWithNode() {
  const page = joinVendorPage(VENDOR);
  mkdirSync(DIST, { recursive: true });
  writeFileSync(path.join(DIST, "index.html"), page);
  writeFileSync(
    path.join(DIST, "test.html"),
    '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">' +
      "<style>body{margin:0}[hidden]{display:none!important}</style></head><body>" +
      page +
      "</body></html>",
  );
  console.log(`${Buffer.byteLength(page)} bytes -> dist/index.html (node)`);
}

function buildWithPython() {
  try {
    execFileSync("python3", [path.join(VENDOR, "build.py")], { stdio: "inherit" });
  } catch (err) {
    console.error("\npython3 could not run build.py. Use the Node builder instead:\n  npm run blueprint:build -- --node\n");
    throw err;
  }
}

if (useNode) buildWithNode();
else buildWithPython();

const html = readFileSync(path.join(DIST, "index.html"), "utf8");
// JSON, not a .ts module: the page is DATA (the vendor's browser code), and the
// repo's source scanners read every .ts file. As a 235 KB one-line .ts string it
// made no-inline-role-lists.test.ts seven times slower and timed it out in CI
// (Oct 8, 2026). The readable source is vendor/event-blueprint/src/.
writeFileSync(OUT, JSON.stringify({ generatedBy: "scripts/blueprint-build.mjs", source: "vendor/event-blueprint/dist/index.html", html }) + "\n");
console.log(`${Buffer.byteLength(html)} bytes -> ${path.relative(ROOT, OUT)}`);

// The fixed option lists the server-side AI prompts name (plan §4.6), read
// from the vendor's own data.js and bench.js in a sandbox, so the server's
// prompts and the page's pickers can never offer different options.
const catalogSource =
  ["data.js", "bench.js"].map((f) => readFileSync(path.join(VENDOR, "src", f), "utf8")).join("\n") +
  "\n;({ TYPES: TYPES.map((t) => ({ id: t.id, n: t.n })), FORMATS, GOALS, MOODS, LANGS, LOOKS, SETTINGS, FEATURES, ACCESS, REGULATED, LAYOUT_NAMES })";
const catalogs = vm.runInNewContext(catalogSource, {}, { timeout: 2000 });
writeFileSync(
  CATALOGS_OUT,
  `// GENERATED by scripts/blueprint-build.mjs from vendor/event-blueprint/src/{data,bench}.js.\n` +
    `// Do not edit: the option lists the Blueprint's server-side AI prompts name.\n` +
    `export const BLUEPRINT_CATALOGS = ${JSON.stringify(catalogs, null, 2)} as const;\n`,
);
console.log(`catalogs -> ${path.relative(ROOT, CATALOGS_OUT)}`);

// The vendor's own completeness rules for the server (plan §4.5): data.js and
// bench.js, then app.js from the top of its closure up to the change-tracking
// section, which holds blank(), sanitise(), checks() and score() and touches
// no DOM until called. The server runs exactly the rules the page shows, so
// "complete" can never mean two things. src/lib/blueprint/vendor-rules.ts
// evaluates it in a sandbox.
const RULES_OUT = path.join(ROOT, "src/lib/blueprint/vendor-rules.generated.json");
const appSrc = readFileSync(path.join(VENDOR, "src/app.js"), "utf8");
const OPEN = "(function () {\n";
const CLOSE = "  // ---------- changes since the last submission ----------";
const from = appSrc.indexOf(OPEN);
const to = appSrc.indexOf(CLOSE);
if (from < 0 || to < 0 || to < from) throw new Error("vendor app.js markers moved: update the rules slice in scripts/blueprint-build.mjs");
const rulesSource =
  ["data.js", "bench.js"].map((f) => readFileSync(path.join(VENDOR, "src", f), "utf8")).join("\n") +
  "\n" +
  appSrc.slice(from + OPEN.length, to) +
  "\n;({ sanitise, score, parseWhen })";
writeFileSync(RULES_OUT, JSON.stringify({ generatedBy: "scripts/blueprint-build.mjs", source: rulesSource }) + "\n");
console.log(`rules -> ${path.relative(ROOT, RULES_OUT)}`);
