#!/usr/bin/env node
/**
 * Rebuild the Event Blueprint page EA-SYS serves at /blueprint.
 *
 *   npm run blueprint:build             # the vendor's own build.py (python3)
 *   npm run blueprint:build -- --node   # the same join in Node, no Python needed
 *   BLUEPRINT_BUILDER=node npm run blueprint:build
 *
 * Two interchangeable builders, owner's choice (Oct 8, 2026): keep the vendor's
 * Python toolchain, with a Node one beside it so a machine without Python is
 * never stuck. Both write the same bytes to vendor/event-blueprint/dist/
 * (index.html, and test.html for the vendor's own browser suites); the
 * page-html test proves the Node join equals dist/index.html.
 *
 * Then the page is written into src/lib/blueprint/page-html.generated.ts, so
 * the server bundle carries it and no file has to be traced into the
 * standalone build. Run this after ANY change under vendor/event-blueprint/src/.
 * Python is never needed on the server: it only ever runs here, on a laptop.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VENDOR = path.join(ROOT, "vendor/event-blueprint");
const DIST = path.join(VENDOR, "dist");
const OUT = path.join(ROOT, "src/lib/blueprint/page-html.generated.ts");

const useNode = process.argv.includes("--node") || process.env.BLUEPRINT_BUILDER === "node";

/** build.py, line for line: part1.html, then the four scripts in one <script>. */
function joinVendorPage(vendorDir) {
  const src = (f) => readFileSync(path.join(vendorDir, "src", f), "utf8");
  const js = ["data.js", "bench.js", "platform.js", "app.js"].map(src).join("\n");
  return src("part1.html") + "\n<script>\n" + js + "\n</script>\n";
}

function buildWithNode() {
  const page = joinVendorPage(VENDOR);
  mkdirSync(DIST, { recursive: true });
  writeFileSync(path.join(DIST, "index.html"), page);
  writeFileSync(
    path.join(DIST, "test.html"),
    '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">' +
      "<style>body{margin:0}[hidden]{display:none!important}</style></head><body>" +
      page +
      "</body></html>",
  );
  console.log(`${Buffer.byteLength(page)} bytes -> dist/index.html (node)`);
}

function buildWithPython() {
  try {
    execFileSync("python3", [path.join(VENDOR, "build.py")], { stdio: "inherit" });
  } catch (err) {
    console.error("\npython3 could not run build.py. Use the Node builder instead:\n  npm run blueprint:build -- --node\n");
    throw err;
  }
}

if (useNode) buildWithNode();
else buildWithPython();

const html = readFileSync(path.join(DIST, "index.html"), "utf8");
// Stored base64: the page is the vendor's BROWSER code (empty catch blocks, a
// Google Fonts link), and as plain text inside src/ it reads as server code to
// the repo's text gates. The readable source is vendor/event-blueprint/src/.
writeFileSync(
  OUT,
  `// GENERATED by scripts/blueprint-build.mjs from vendor/event-blueprint/dist/index.html.\n` +
    `// Do not edit: change vendor/event-blueprint/src/ and run \`npm run blueprint:build\`.\n` +
    `// Base64 so the repo's server-code gates do not read the vendor's browser code.\n` +
    `export const BLUEPRINT_PAGE_HTML_BASE64 =\n  ${JSON.stringify(Buffer.from(html).toString("base64"))};\n`,
);
console.log(`${Buffer.byteLength(html)} bytes -> ${path.relative(ROOT, OUT)}`);
