/**
 * The MME product catalogue every organisation starts from: the cost items a
 * budget line can be picked from, with the QuickBooks SKU that Phase 3 maps
 * onto items and classes. Source: the owner's "MME - Products.csv" export of
 * 14 Sep 2026 (203 items; the file carries no prices, so a unit cost is typed
 * per budget). Each item is assigned to one of the seed categories by its SKU
 * group, with a few named exceptions; an admin can move any item afterwards on
 * the Products page. The two "Discount given" contra items are seeded archived:
 * they exist for the accounting mapping and are never a thing to budget for.
 * Client-safe: constants only. SKUs are STABLE KEYS and are never edited.
 */
export interface BudgetProductSeed {
  sku: string;
  name: string;
  /** A `BUDGET_CATEGORY_SEED` code. */
  category: string;
  /** Seeded archived (contra accounts). */
  active?: boolean;
}

/** A SKU: letters, digits, dot, dash, underscore, up to 40 characters. */
export const BUDGET_PRODUCT_SKU_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,39}$/;

export const BUDGET_PRODUCT_SEED: readonly BudgetProductSeed[] = [
  { sku: "500101", name: "CME Application Fees", category: "COMPLIANCE" },
  { sku: "500102", name: "CME Application Processing", category: "COMPLIANCE" },
  { sku: "500103", name: "CME Documents Preparation", category: "COMPLIANCE" },
  { sku: "500104", name: "CME E-Certificate", category: "COMPLIANCE" },
  { sku: "500105", name: "CME Evaluation Survey", category: "COMPLIANCE" },
  { sku: "500106", name: "CME Tracking", category: "COMPLIANCE" },
  { sku: "500107", name: "Live Poll Session Survey", category: "COMPLIANCE" },
  { sku: "500201", name: "Delegate Badges & Branded Lanyards", category: "PRINT" },
  { sku: "500202", name: "Abstract Reviewer & Workflow Portal", category: "TECH" },
  { sku: "500203", name: "Abstract Reviewer Access", category: "TECH" },
  { sku: "500204", name: "Abstract Submission Portal", category: "TECH" },
  { sku: "500205", name: "Abstract Submission Processing", category: "TECH" },
  { sku: "500206", name: "Conference App Design & Build", category: "TECH" },
  { sku: "500207", name: "Delegate Registration Portal", category: "TECH" },
  { sku: "500208", name: "Delegate Support Portal", category: "TECH" },
  { sku: "500209", name: "E-Payment Gateway", category: "TECH" },
  { sku: "500210", name: "Housing & Accommodation Portal", category: "TECH" },
  { sku: "500211", name: "Live Chat Service (Office Hours)", category: "TECH" },
  { sku: "500301", name: "Banner / Rollup Design & Production", category: "PRINT" },
  { sku: "500302", name: "Certificate Printing", category: "PRINT" },
  { sku: "500303", name: "Eye Drop Flags Production", category: "PRINT" },
  { sku: "500304", name: "Facebook PPC Advert Campaign", category: "MARKETING" },
  { sku: "500305", name: "Final Program Printing", category: "PRINT" },
  { sku: "500306", name: "Flyer Printing", category: "PRINT" },
  { sku: "500307", name: "Frames for Certificate", category: "PRINT" },
  { sku: "500308", name: "Invitation Card Printing with Envelopes", category: "PRINT" },
  { sku: "500309", name: "Photographer & Videographer", category: "MARKETING" },
  { sku: "500310", name: "Pocket Program Book - Printing", category: "PRINT" },
  { sku: "500311", name: "Post Card Printing", category: "PRINT" },
  { sku: "500312", name: "Poster Printing", category: "PRINT" },
  { sku: "500313", name: "Stage and Backdrop Design", category: "MARKETING" },
  { sku: "500314", name: "Table Flag Production", category: "PRINT" },
  { sku: "500315", name: "Venue Branding Production", category: "PRINT" },
  { sku: "500316", name: "Invitation Card Printing", category: "PRINT" },
  { sku: "500317", name: "Press Release", category: "MARKETING" },
  { sku: "500318", name: "Video Editing", category: "MARKETING" },
  { sku: "500319", name: "Abstract Book Design Digital Format Per Page", category: "MARKETING" },
  { sku: "500320", name: "Abstract Book Design Print Format", category: "MARKETING" },
  { sku: "500321", name: "Abstract Book Production - Print Format", category: "PRINT" },
  { sku: "500322", name: "Announcement Design Digital Format Per Page", category: "MARKETING" },
  { sku: "500323", name: "Announcement Design Print Format", category: "MARKETING" },
  { sku: "500324", name: "Announcement Production - Print Format", category: "PRINT" },
  { sku: "500325", name: "Attendance Certificate Design Digital Format", category: "MARKETING" },
  { sku: "500326", name: "Bus Signage Design Print Format", category: "MARKETING" },
  { sku: "500327", name: "Bus Signage Printing", category: "PRINT" },
  { sku: "500328", name: "Conference Email Account", category: "MARKETING" },
  { sku: "500329", name: "Conference Landing Page", category: "MARKETING" },
  { sku: "500330", name: "Conference Web Site", category: "MARKETING" },
  { sku: "500331", name: "Conference Web Site Updates Per Month", category: "MARKETING" },
  { sku: "500332", name: "Domain Registration & Hosting", category: "MARKETING" },
  { sku: "500333", name: "Email Marketing Per Mailer", category: "MARKETING" },
  { sku: "500334", name: "Event Brand Identity & Artwork", category: "MARKETING" },
  { sku: "500335", name: "Facebook Account Setup", category: "MARKETING" },
  { sku: "500336", name: "Facebook Page Management", category: "MARKETING" },
  { sku: "500337", name: "Final program Design Digital Format Per Page", category: "MARKETING" },
  { sku: "500338", name: "Final program Design Print Format", category: "MARKETING" },
  { sku: "500339", name: "Final program Production - Print Format", category: "PRINT" },
  { sku: "500340", name: "Flyer Design Print Format (A4)", category: "MARKETING" },
  { sku: "500341", name: "Folder's Production", category: "PRINT" },
  { sku: "500342", name: "Function Ticket Design Print Format", category: "MARKETING" },
  { sku: "500343", name: "Google Adwords Account Setup", category: "MARKETING" },
  { sku: "500344", name: "Google Adwords PPC Campaign", category: "MARKETING" },
  { sku: "500345", name: "Google Analytics Setup", category: "MARKETING" },
  { sku: "500346", name: "HTML Newsletters", category: "MARKETING" },
  { sku: "500347", name: "HTML Page Design Digital Format", category: "MARKETING" },
  { sku: "500348", name: "Invitation Design Digital Format", category: "MARKETING" },
  { sku: "500349", name: "Invitation Design Print Format", category: "MARKETING" },
  { sku: "500350", name: "Linkedin Account Management", category: "MARKETING" },
  { sku: "500351", name: "Pocket Program Book - Design", category: "MARKETING" },
  { sku: "500352", name: "Post Card Design Print Format", category: "MARKETING" },
  { sku: "500353", name: "Post Event Report", category: "MARKETING" },
  { sku: "500354", name: "Poster Design Print Format", category: "MARKETING" },
  { sku: "500355", name: "Search Engine Optimisation", category: "MARKETING" },
  { sku: "500356", name: "SMS Text Campaign (per sms)", category: "MARKETING" },
  { sku: "500357", name: "Social Function Ticket Printing", category: "PRINT" },
  { sku: "500358", name: "Social Media Frame", category: "MARKETING" },
  { sku: "500359", name: "Social Media Posts Design", category: "MARKETING" },
  { sku: "500360", name: "Sponsorship Prospectus Design Digital Format Per Page", category: "MARKETING" },
  { sku: "500361", name: "Sponsorship Prospectus Design Print Format", category: "MARKETING" },
  { sku: "500362", name: "Sponsorship Prospectus Production - Print Format", category: "PRINT" },
  { sku: "500363", name: "Stock Images", category: "MARKETING" },
  { sku: "500364", name: "Story Board Writing", category: "MARKETING" },
  { sku: "500365", name: "Twitter Account Management", category: "MARKETING" },
  { sku: "500366", name: "Video Animation & FX", category: "MARKETING" },
  { sku: "500367", name: "Video Recording Cameraman", category: "MARKETING" },
  { sku: "500368", name: "Voice Over Recording", category: "MARKETING" },
  { sku: "500401", name: "Staff - Visa", category: "STAFFING" },
  { sku: "500402", name: "Staff Accommodation", category: "STAFFING" },
  { sku: "500403", name: "Staff Air Ticket", category: "STAFFING" },
  { sku: "500404", name: "Staff Per-Diem", category: "STAFFING" },
  { sku: "500405", name: "Staff Refreshments", category: "STAFFING" },
  { sku: "500406", name: "Staff Transportation", category: "STAFFING" },
  { sku: "500407", name: "Staff Hire", category: "STAFFING" },
  { sku: "500501", name: "Faculty Dinner", category: "FNB" },
  { sku: "500502", name: "Welcome Reception", category: "FNB" },
  { sku: "500503", name: "Conference Dinner", category: "FNB" },
  { sku: "500601", name: "Committee / VIP Trophies", category: "MISC" },
  { sku: "500602", name: "Delegate Packs", category: "MISC" },
  { sku: "500603", name: "Speaker Giveaways", category: "MISC" },
  { sku: "500604", name: "Education Grant", category: "MISC" },
  { sku: "500701", name: "Bus Transfers - 35 Seater - 8 Hours", category: "TRAVEL" },
  { sku: "500702", name: "Bus Transfers - 50 Seater - 8 Hours", category: "TRAVEL" },
  { sku: "500703", name: "Chauffeur Transfer per way (Dubai / Sharjah)", category: "TRAVEL" },
  { sku: "500704", name: "Chauffeur Transfers - Others", category: "TRAVEL" },
  { sku: "500705", name: "Air Travel Booking Fee", category: "TRAVEL" },
  { sku: "500706", name: "Hotel Accommodation", category: "ACCOMMODATION" },
  { sku: "500707", name: "Visa Application Charge", category: "TRAVEL" },
  { sku: "500708", name: "Visa Processing Charge", category: "TRAVEL" },
  { sku: "500801", name: "DTCM Event Permit", category: "COMPLIANCE" },
  { sku: "500802", name: "DTCM Permit Application Processing", category: "COMPLIANCE" },
  { sku: "500803", name: "DTCM Ticketing Permit", category: "COMPLIANCE" },
  { sku: "500804", name: "DTCM Ticketing Permit Application Processing", category: "COMPLIANCE" },
  { sku: "500805", name: "Society Endorsement Fees", category: "COMPLIANCE" },
  { sku: "500806", name: "Society Royalty Fees", category: "COMPLIANCE" },
  { sku: "500807", name: "TCA Event Permit", category: "COMPLIANCE" },
  { sku: "500808", name: "TCA Event Permit Faculty Application", category: "COMPLIANCE" },
  { sku: "500809", name: "TCA Permit Application Processing", category: "COMPLIANCE" },
  { sku: "500810", name: "DTCM Event Permit Faculty Application", category: "COMPLIANCE" },
  { sku: "500811", name: "DTCM Ticketing Integration", category: "COMPLIANCE" },
  { sku: "500812", name: "Society Endorsement - DHA", category: "COMPLIANCE" },
  { sku: "500813", name: "Society Endorsement - EHS", category: "COMPLIANCE" },
  { sku: "500901", name: "Bank Charges", category: "MISC" },
  { sku: "500902", name: "Conference Stationery", category: "MISC" },
  { sku: "500903", name: "Event Florist", category: "MISC" },
  { sku: "500904", name: "Freight and delivery - COS", category: "MISC" },
  { sku: "500905", name: "MC Fees", category: "MISC" },
  { sku: "500906", name: "Misc. Expenses", category: "MISC" },
  { sku: "500907", name: "Overseas Marketing Trips", category: "MARKETING" },
  { sku: "500908", name: "Venue Internet Charges", category: "TECH" },
  { sku: "500909", name: "Courier Charges", category: "MISC" },
  { sku: "500910", name: "HCP Registration", category: "MISC" },
  { sku: "500911", name: "Shipping Charges", category: "MISC" },
  { sku: "500912", name: "Cancellation Charges", category: "MISC" },
  { sku: "500913", name: "Communication Costs", category: "MISC" },
  { sku: "500914", name: "Conference Consumables", category: "MISC" },
  { sku: "500915", name: "Currency Variation", category: "MISC" },
  { sku: "500916", name: "Event Insurance", category: "MISC" },
  { sku: "500917", name: "Labour Charges", category: "MISC" },
  { sku: "500918", name: "Venue Parking Access Cards", category: "VENUE" },
  { sku: "500919", name: "Subcontractors - COS", category: "MISC" },
  { sku: "510001", name: "Event Staff Per Hour", category: "STAFFING" },
  { sku: "510002", name: "PCO Management Fee", category: "STAFFING" },
  { sku: "510003", name: "Staff Travel Per Diem", category: "STAFFING" },
  { sku: "510004", name: "Marketing & Promotions", category: "MARKETING" },
  { sku: "510005", name: "Accounting & Finance", category: "STAFFING" },
  { sku: "510006", name: "Conference Director", category: "STAFFING" },
  { sku: "510007", name: "Conference Producer", category: "STAFFING" },
  { sku: "510008", name: "Designer", category: "STAFFING" },
  { sku: "510009", name: "Exhibition Management", category: "STAFFING" },
  { sku: "510010", name: "Housing & Accommodation", category: "STAFFING" },
  { sku: "510011", name: "PCO Sale Incentive", category: "STAFFING" },
  { sku: "510012", name: "Session Management", category: "STAFFING" },
  { sku: "510013", name: "Social Functions", category: "STAFFING" },
  { sku: "510014", name: "Sponsorship Management", category: "STAFFING" },
  { sku: "510015", name: "Transportation Management", category: "STAFFING" },
  { sku: "510016", name: "Visa Assistance", category: "STAFFING" },
  { sku: "510017", name: "Web Administrator", category: "STAFFING" },
  { sku: "510101", name: "Experts Tours", category: "FACULTY" },
  { sku: "510102", name: "Medical Content - One Day", category: "FACULTY" },
  { sku: "510103", name: "Medical Content - Two Days", category: "FACULTY" },
  { sku: "510104", name: "Medical Content - Half Day", category: "FACULTY" },
  { sku: "510105", name: "Scientific Program", category: "FACULTY" },
  { sku: "510201", name: "Speaker Accommodation", category: "FACULTY" },
  { sku: "510202", name: "Speaker Activity", category: "FACULTY" },
  { sku: "510203", name: "Speaker Air Ticket", category: "FACULTY" },
  { sku: "510204", name: "Speaker Chauffeur Transfers", category: "FACULTY" },
  { sku: "510205", name: "Speaker Honorarium", category: "FACULTY" },
  { sku: "510206", name: "Speaker Per Diem", category: "FACULTY" },
  { sku: "510207", name: "Speaker Reimbursement", category: "FACULTY" },
  { sku: "510208", name: "Speaker Visa Application Charges", category: "FACULTY" },
  { sku: "510209", name: "Speaker Air Travel Allowance", category: "FACULTY" },
  { sku: "510301", name: "Audio Video Equipment Rental", category: "AV" },
  { sku: "510302", name: "Digital Poster Kiosk", category: "AV" },
  { sku: "510303", name: "Exhibition Stand Build", category: "AV" },
  { sku: "510304", name: "Furniture Rental", category: "AV" },
  { sku: "510305", name: "Laptop Rental", category: "AV" },
  { sku: "510306", name: "Poster Area Build", category: "AV" },
  { sku: "510307", name: "Power Supply", category: "AV" },
  { sku: "510308", name: "Stage & Backdrop Build", category: "AV" },
  { sku: "510309", name: "Networking & Cabling", category: "TECH" },
  { sku: "510310", name: "Translation Services", category: "TRANSLATION" },
  { sku: "510311", name: "Venue Carpeting", category: "AV" },
  { sku: "510312", name: "Virtual Software - Rental", category: "TECH" },
  { sku: "510313", name: "Badge Scanners", category: "REGOPS" },
  { sku: "510314", name: "POS Machines Rental - Per Day", category: "REGOPS" },
  { sku: "510315", name: "Registration Equipment Rental", category: "REGOPS" },
  { sku: "510316", name: "Speakers Lounge Build", category: "AV" },
  { sku: "510317", name: "Special Features", category: "AV" },
  { sku: "510318", name: "Venue Barriers", category: "AV" },
  { sku: "510319", name: "Venue Wifi Network", category: "TECH" },
  { sku: "510320", name: "Voting System", category: "AV" },
  { sku: "510321", name: "Voting System Lost Device Penalty", category: "AV" },
  { sku: "510322", name: "Voting System Operator", category: "AV" },
  { sku: "510401", name: "Day Delegate Rate", category: "VENUE" },
  { sku: "510402", name: "Meeting Rooms", category: "VENUE" },
  { sku: "510403", name: "Session Halls", category: "VENUE" },
  { sku: "510404", name: "Venue Rental & Breakout Rooms", category: "VENUE" },
  { sku: "510405", name: "Gala Dinner Venue", category: "VENUE" },
  { sku: "510406", name: "Organiser's Office", category: "VENUE" },
  { sku: "510407", name: "VIP Catering for OC", category: "FNB" },
  { sku: "510408", name: "VIP Majlis & Protocol", category: "VENUE" },
  { sku: "510501", name: "Discounts given - COS", category: "MISC", active: false },
  { sku: "510600", name: "Discount Given - Cost of Sales", category: "MISC", active: false },
];
